/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qihoo_cleandroid_sdk_imageclassfier_core_classfier_process_CustomClassifier */

#ifndef _Included_com_qihoo_cleandroid_sdk_imageclassfier_core_classfier_process_CustomClassifier
#define _Included_com_qihoo_cleandroid_sdk_imageclassfier_core_classfier_process_CustomClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qihoo_cleandroid_sdk_imageclassfier_core_classfier_process_CustomClassifier
 * Method:    getPredictResult
 * Signature: ([[[[F[[FII)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_com_qihoo_cleandroid_sdk_imageclassfier_core_classfier_process_CustomClassifier_getPredictResult
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
